### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by NaraSakamoto** [biancaBezerra/SAP011-fleet-management-api_biancaBezerra#2]
Bia,

Deixo aqui algumas sugestões para você continuar a sua jornada de estudos!

Para continuar se aprimorando como Desenvolvedora Backend Java, sugiro se aprofundar em:

1. Linguagem Java. E para isso deixo algumas sugestões de estudo prático de Java para você escolher:

 - [ ] [exercism](https://exercism.org/tracks/java)
 - [ ] [Code Academy](https://www.codecademy.com/learn/learn-java)
 - [ ] [Hacker Rank](https://www.hackerrank.com/domains/java)
 
2.   Conceitos de Programação Orientada a Objetos. Sugiro alguns cursos gratuitos, escolha um para fazer:

 - [ ] [Fundação Bradesco](https://www.ev.org.br/cursos/introducao-a-programacao-orientada-a-objetos-poo), que inclusive foi vc que me indicou! Dei uma olhada no conteúdo do curso e achei que abrange temas bem necessários!
 - [ ] [Dev Dojo - Maratona Java](https://youtu.be/VKjFuX91G5Q?feature=shared). Esse curso é bem atual, vale a pena. 
 
3. Se aprofundar na construção de APIs REST usando Spring Boot. Sugiro alguns cursos gratuitos como:

 - [ ] [Spring Boot 3 | Complete Course 2023](https://www.youtube.com/watch?v=wlYvA2b1BWI).
 - [ ] [Desafio Vagas: API de tarefas com Spring Boot!](https://www.youtube.com/watch?v=IjProDV001o). Esse vídeo a apresentadora mostra um desafio de uma vaga de emprego.
 - [ ] [Dev Dojo - Spring Boot Essentials 2](https://youtube.com/playlist?list=PL62G310vn6nFBIxp6ZwGnm8xMcGE3VA5H&feature=shared)

4. Inicie seus estudos em Cloud Computing. Como muitas empresas utilizam AWS, recomendo que inicie seus estudos por ela. 
 - [ ] [AWS Educate](https://aws.amazon.com/pt/education/awseducate/?trk=8c29b82a-1d1c-47a7-a99b-21eafe50c48e&sc_channel=el). Neste link você encontrará conteúdos que te ajudarão com os estudos de Cloud Computing. É gratuito e bem prático. 
 - [ ] [AWS Certification](https://aws.amazon.com/pt/certification/?nc2=sb_ce_co). Neste link você poderá buscar por uma certificação. Infelizmente a certificação é paga, mas o estudo é gratuito. Vale a pena dar uma olhada.

Revisando os seus Objetivos de Aprendizagem de cada um dos projetos da Laboratória, deixo aqui algumas sugestões de estudos que podem complementar o seu aprendizado.
 
Sobre HTML Semântico, veja um pouco sobre isso nesses conteúdos abaixo, mas pratique! Tente aplicar em seus próximos HTMLs:
- [ ] [Devmedia HTML Semântico](https://www.devmedia.com.br/html-semantico-conheca-os-elementos-semanticos-da-html5/38065)
- [ ] [Elementos semânticos do HTML5 explicados](https://www.freecodecamp.org/portuguese/news/elementos-semanticos-do-html5-explicados/)

Sobre o git: 

- [ ] [Learn git Branching - Tutorial](https://learngitbranching.js.org/?locale=pt_BR). Nesse tutorial vc vai aprender como usar as branches do git. O tutorial é dinâmico e simula um terminal. 
- [ ] [Conventional Commits](https://www.conventionalcommits.org/pt-br/v1.0.0/). Nesse site você encontra uma convenção de nomes e mensagens de commits que é bem comum de se usar. 

Sobre Interfaces Java: 

- [ ]  Você pode iniciar seus estudos por esses conteúdos que deixo abaixo:
    - [ ]  [POO em Java - Compreendendo as Interfaces](https://www.dio.me/articles/poo-em-java-compreendendo-as-interfaces)
    - [ ]  [Interfaces em Java explicadas com exemplos](https://www.freecodecamp.org/portuguese/news/interfaces-em-java-explicadas-com-exemplos/)
    - [ ]  [Exercício sobre Interfaces - Exercism](https://exercism.org/tracks/java/concepts/interfaces)
    - [ ]  [Interfaces - Java Documentation](https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html)
    
Sobre as Collections do Java (principalmente HashMap e HashSet):
- [ ] [HashMap in Java - Geek for geeks](https://www.geeksforgeeks.org/java-util-hashmap-in-java-with-examples/)
- [ ] [Dictionaries and Maps - HackerRank](https://www.hackerrank.com/challenges/30-dictionaries-and-maps/tutorial)
- [ ] [HashSet in Java - Geek for geeks](https://www.geeksforgeeks.org/hashset-in-java/)
- [ ] [Java HashSet - HackerRank](https://www.hackerrank.com/challenges/java-hashset/problem?isFullScreen=true)

Parabéns pela sua jornada ao longo do Bootcamp, Bia! Você aproveitou bastante todas as oportunidades de aprendizagem!
Foi só o começo da sua carreira de sucesso na Tecnologia!

Beijos!
